GRANT USAGE ON SCHEMA public TO sinfomik_app;
GRANT CREATE ON SCHEMA public TO sinfomik_app; -- jika perlu buat table
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sinfomik_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sinfomik_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO sinfomik_app;

-- Agar hak berlaku untuk objek yang dibuat nanti
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sinfomik_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sinfomik_app;